### ISSUE TITLE
Spark should provide real SSO functionality

### ISSUE THREAD

**Issue by rootux** [Midburn/spark#279] opened 2017-04-12 09:41 UTC
Right now spark support normal login
We need real Sso so users could 'Login with spark'. 
The idea is that the browser will know the credentials and that certified apps can login and get users info through spark

**Comment by omerpines** [comment] 2017-04-12 10:07
Guys, this is an urgent task since people don't remember their password to their Midburn Profile (Sometimes they don't even remember their email) and this is causing people to leave the other platforms without logging in (currently only Dreams but soon enough MidMarket, Spark - Camps and Volunteers...)

We need to add an SSO module in Spark that can handle sessions, linked users from other services. I am pretty sure there is something ready-made we can use (see FB SSO or Gmail SSO).

This will make all our systems with a seamless login.

Open issues:
1. Consider mobile connection to Spark.
2. Logout of session
3. SSO per app or for all apps automatically (similar to Google account SSO).
4. Improve security

**Comment by OriHoch** [comment] 2017-04-13 06:01
#### related / possibly duplicate issues
* #281 - Spark should move towards OAuth
* #288 - Implement sso functionality

**Comment by OriHoch** [comment] 2017-04-13 06:02
I'll be working on issue #288

**Comment by LeonFedotov** [comment] 2017-04-13 08:48
duplicate of #288

**Closed as completed by LeonFedotov** 2017-04-13 08:48 UTC
