### ISSUE TITLE
Spark should move towards OAuth

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#281] opened 2017-04-12 10:23 UTC
In the distant future

**Comment by OriHoch** [comment] 2017-04-13 05:59
please provide some details - 
* why OAuth specifically?
* what's the use case specifically for OAuth
* how it related to other SSO issues like #279 / #288

**Comment by OriHoch** [comment] 2017-04-13 06:02
#### related / possibly duplicate issues
* #279 - Spark should provide real SSO functionality
* #288 - Implement sso functionality

**Comment by OriHoch** [comment] 2017-04-13 06:02
I'll be working on issue #288

**Comment by LeonFedotov** [comment] 2017-04-13 08:47
ok closing this as duplicate of #288

**Closed as completed by LeonFedotov** 2017-04-13 08:47 UTC
