### ISSUE TITLE
Setup & Deploy to Staging Server

### ISSUE THREAD

**Issue by ripper234** [Midburn/spark#34] opened 2017-01-18 10:49 UTC
Every commit to master, the code should be auto-deployed to staging (after/if tests pass).

**Comment by OriHoch** [comment] 2017-01-23 13:41
first part of this issue is done in #45 - building deployment package automatically on every commit to master and upload this package to slack 

next step is to do the actual deployment of this pacakge (simple bash script can do it..)

**Comment by OriHoch** [comment] 2017-01-23 13:42
this is a duplicate of #31

**Closed as completed** 2017-01-23 13:43 UTC
