### ISSUE TITLE
Midburn association button needs to be removed

### ISSUE THREAD

**Issue by pandamichal** [Midburn/spark#592] opened 2018-01-25 15:10 UTC
The feature which updating whether or not your a Hamuta member is not active and does not have any database. In addition, the form is not really sent.
In the meanwhile, we need to remove the button from the menu until it will be fixed.

**Comment by pandamichal** [comment] 2018-02-26 15:20
@amotenko  Can we do that?

**Comment by amotenko** [comment] 2018-02-26 15:38
Going down today!

pandamichal <notifications@github.com> schrieb am Mo., 26. Feb. 2018, 17:20:

**Comment by pandamichal** [comment] 2018-03-01 11:55
Hey :-) the button is still there...

**Comment by ArtyomKa** [comment] 2018-03-01 14:47
yes. hence the issue is still open. 😉

**Comment by amotenko** [comment] 2018-03-01 15:57
Luckily @enoodle is assigned to it :)

**Closed as completed** 2018-03-04 15:21 UTC
Labels: good first issue
